### ISSUE TITLE
1.17.1

### ISSUE THREAD

**Issue by Foxite** [fraenkelc/RCONNewlineFix#2]
Hey, I was hoping you could port this to 1.17.1. Any luck?

**Comment by fraenkelc** [comment]
Hi, it looks like forge already ships their own patch for 1.17.1:
https://github.com/MinecraftForge/MinecraftForge/blob/b027a92dd287d6810a9fdae4d4b1e1432d7dc9cc/patches/minecraft/net/minecraft/server/rcon/RconConsoleSource.java.patch

**Comment by Foxite** [comment]
Nice, thanks. Too bad it's only Forge, but I suppose it should be possible to write a mixin for fabric.
